/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devfox.SatisfactoryAssistant;

import com.devfox.recipes.Recipe;
import com.devfox.recipes.RecipeEvaluator;
import com.devfox.recipes.RecipeGenerator;
import org.xml.sax.SAXException;

import javax.xml.parsers.ParserConfigurationException;
import java.io.File;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, SAXException, ParserConfigurationException {
        Recipe[] firstRecipeSet = RecipeGenerator.readRecipesFromXMLFile(new File(ClassLoader.getSystemResource("recipes.xml").getPath()));
        RecipeEvaluator.reportAmountOfEachComponentPerMin(firstRecipeSet, "IRON_PLATE",60);
    }
}
