/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devfox.SatisfactoryAssistant;

import org.xml.sax.SAXException;
import javax.xml.parsers.ParserConfigurationException;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, SAXException, ParserConfigurationException {

    }
}
